# Generated by Django 5.1.1 on 2024-10-05 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=40)),
                ('experience', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=70)),
                ('salery_type', models.FloatField()),
                ('work_type', models.TextField()),
                ('job_post', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.manager'),
        ),
    ]
