# Generated by Django 5.1.1 on 2024-10-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0005_student_teacher_delete_classroom_delete_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
