# Generated by Django 5.1.1 on 2024-10-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IteamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
                ('sub_category', models.CharField(max_length=400)),
                ('item_name', models.CharField(max_length=255)),
                ('item_location', models.CharField(max_length=300)),
                ('item_id', models.CharField(max_length=25)),
                ('item_description', models.TextField()),
                ('item_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
