# Generated by Django 5.1.1 on 2024-10-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IteamList',
            new_name='ItemList',
        ),
    ]
